"""First migration

Revision ID: 9e95673f2c46
Revises: 
Create Date: 2021-03-05 17:21:14.007864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e95673f2c46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aqi_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aqi_alerts_id'), 'aqi_alerts', ['id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_city'), 'sensors', ['city'], unique=False)
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_index(op.f('ix_sensors_zone'), 'sensors', ['zone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('aqi_alert_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['aqi_alerts.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aqi_alert_notifications_id'), 'aqi_alert_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aqi_alert_notifications_id'), table_name='aqi_alert_notifications')
    op.drop_table('aqi_alert_notifications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensors_zone'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_city'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_aqi_alerts_id'), table_name='aqi_alerts')
    op.drop_table('aqi_alerts')
    # ### end Alembic commands ###
