version: "3.9"
services:
  migration:
    image: notivize-diy
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - alembic
      - upgrade
      - head
    volumes:
      - sqlite-volume:/notivize-diy
      - ./src:/notivize-diy/src
      - ./alembic:/notivize-diy/alembic
      - ./.env:/notivize-diy/.env
  api:
    image: notivize-diy
    command:
      # XXX: Beware that you will need to `ctrl-c` twice to kill "docker-compose up" with the "reload" argument
      - --reload
    ports:
      - "8000:8000"
    volumes:
      - sqlite-volume:/notivize-diy
      - ./src:/notivize-diy/src
      - ./alembic:/notivize-diy/alembic
      - ./.env:/notivize-diy/.env
    depends_on:
      - migration

volumes:
  sqlite-volume:
