version: "3.9"
services:
  migration:
    image: notivize-diy
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - alembic
      - upgrade
      - head
    volumes:
      - ./:/notivize-diy
  api:
    image: notivize-diy
    command:
      # XXX: Beware that you will need to `ctrl-c` twice to kill "docker-compose up" with the "reload" argument
      - --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/notivize-diy
    depends_on:
      - migration
